// Hand-curated location -> act mapping for locations that the wiki's
// "List of magic items in Act X" pages don't cover (they only transclude
// ~36 coarse location tables; item_locations uses finer-grained names).
// Merged with the scraped act mapping in scrape-items.mjs; scraped data wins.
export const LOCATION_ACT_OVERRIDES = {
  // ---- Act 1: Wilderness / Underdark / Mountain Pass ----
  "Crèche Y'llek": 'Act 1',
  "Creche Y'llek": 'Act 1',
  'Rosymorn Monastery': 'Act 1',
  'Ebonlake Grotto': 'Act 1',
  'Zhentarim Basement': 'Act 1',
  'The Hollow': 'Act 1',
  'Hollow': 'Act 1',
  'Adamantine Forge': 'Act 1',
  'Whispering Depths': 'Act 1',
  'The Festering Cove': 'Act 1',
  'Arcane Tower': 'Act 1',
  'Selûnite Outpost': 'Act 1',
  'Decrepit Village': 'Act 1',
  'Worg Pens': 'Act 1',
  'Defiled Temple': 'Act 1',
  'Inner Sanctum': 'Act 1',
  'Sacred Pool': 'Act 1',
  'Owlbear Nest': 'Act 1',
  'Dank Crypt': 'Act 1',
  'Overgrown Tunnel': 'Act 1',
  'Underground Passage': 'Act 1',
  'Risen Road': 'Act 1',
  'Risen Road Toll House': 'Act 1',
  'Riverside Teahouse': 'Act 1',
  'Ancient Lair': 'Act 1',
  'Tiefling Hideout': 'Act 1',
  'Abandoned Windmill': 'Act 1',
  'Western Beach': 'Act 1',
  'Abandoned Refuge': 'Act 1',
  'Wilderness': 'Act 1',

  // ---- Act 2: Shadow-Cursed Lands / Moonrise / Gauntlet of Shar ----
  'Shadow-Cursed Lands': 'Act 2',
  'House of Healing': 'Act 2',
  'House of Healing Morgue': 'Act 2',
  'Reithwin Tollhouse': 'Act 2',
  'Reithwin Graveyard': 'Act 2',
  'Mason’s Guild': 'Act 2',
  "Mason's Guild": 'Act 2',
  'Moonrise Towers Prison': 'Act 2',
  'Moonrise Towers Rooftop': 'Act 2',
  'Oubliette': 'Act 2',
  'Last Light Inn Cellar': 'Act 2',
  'Last Light Inn - Cellar': 'Act 2',
  'The Waning Moon': 'Act 2',
  'Waning Moon': 'Act 2',
  'House in Deep Shadows': 'Act 2',
  "Old Garlow's Place": 'Act 2',
  'Grand Mausoleum': 'Act 2',
  'Cloister of Sombre Embrace': 'Act 2',
  "Apothecary's Cellar": 'Act 2',
  'Dread Hollow': 'Act 2',
  'Decrepit Sanctuary': 'Act 2',

  // ---- Act 3: Rivington / Wyrm's Crossing / Lower City ----
  'Circus of the Last Days': 'Act 3',
  'Murder Tribunal': 'Act 3',
  'House of Hope': 'Act 3',
  "Devil's Fee": 'Act 3',
  'Rivington General': 'Act 3',
  'The Counting House': 'Act 3',
  'Counting House': 'Act 3',
  "Danthelon's Dancing Axe": 'Act 3',
  'Stormshore Tabernacle': 'Act 3',
  'Stormshore Armoury': 'Act 3',
  'Sorcerous Sundries': 'Act 3',
  'Sorcerous Vault': 'Act 3',
  'Lower City Sewers': 'Act 3',
  'Forge of the Nine': 'Act 3',
  "Philgrave's Mansion": 'Act 3',
  'Chromatic Scale': 'Act 3',
  'Steel Watch Foundry': 'Act 3',
  'Open Hand Temple': 'Act 3',
  'Open Hand Temple Cellar': 'Act 3',
  'Bhaal Temple': 'Act 3',
  'Knights of the Shield Hideout': 'Act 3',
  "Ramazith's Tower": 'Act 3',
  "Cazador's Dungeon": 'Act 3',
  'Szarr Palace': 'Act 3',
  "Carm's Garms": 'Act 3',
  "Lady Jannath's Estate": 'Act 3',
  "Elerrathin's Home": 'Act 3',
  "Felogyr's Fireworks": 'Act 3',
  "Highberry's Home": 'Act 3',
  "Lora's House": 'Act 3',
  "The Dragon's Sanctum": 'Act 3',
  'Elfsong Tavern': 'Act 3',
  'Gur Camp': 'Act 3',
  'Heapside Prison': 'Act 3',
  'Upper City': 'Act 3',
  'Guildhall': 'Act 3',
  'Blushing Mermaid': 'Act 3',
  'Flymm Cargo': 'Act 3',
  "Flymm's Cobblers": 'Act 3',
  'Water Queen’s House': 'Act 3',
  "Water Queen's House": 'Act 3',
  "Sharess' Caress": 'Act 3',
  'The Glitter Gala': 'Act 3',
  "Facemaker's Boutique": 'Act 3',
  "Fraygo's Flophouse": 'Act 3',
  "Nortale's Hostel": 'Act 3',
  'Beehive General Goods': 'Act 3',
  'High Hall': 'Act 3',
  'The Lodge - Basement Docks': 'Act 3',
  "Baldur's Gate": 'Act 3',
  'Mortuary': 'Act 3',
  'Durinbold Mausoleum': 'Act 3',
  "Angleiron's Cellar": 'Act 3',
  'Graveyard (Lower City)': 'Act 3',
  'Sharran Sanctuary': 'Act 3',
  "Golbraith's Cellar": 'Act 3',
};
